[package]
name = "mupen64-movie-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
arrayvec = "0.7.2"
thiserror = "1.0.30"
strum = "0.24"
strum_macros = "0.24"
chrono = "0.4.19"
